---
name: 99 Bottles CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          npm install && npm run test
        shell: bash
